### PR TITLE
Refit OxyPlot.Contrib.Wpf against pre-release

### PR DESCRIPTION
**Pull request by VisualMelon**
The WPF libraries don't work at the moment. This is a start on fixing them up.

Having never used them, I'm not sure about the virtual methods that have been lost from `Plot`, and I haven't yet finished implementing legend support.

Related issues:
 - Commentary on XAML/WPF provision: https://github.com/oxyplot/oxyplot/issues/1658#issuecomment-703085959
 - Blocking progress here: https://github.com/oxyplot/oxyplot/pull/1677
 - I think this is a block concern for a 2.1 release, because it's massive backwards compatibility breaker (it would be nice if the solution was just to 'Add a reference to OxyPlot.Contrib.WPF': https://github.com/oxyplot/oxyplot/issues/1671

### CODE REVIEW

**Comment by Jonarw** [comment]
Well I guess the point of moving the WPF-XAML-stuff here was kind of not having to deal with it in the development of the main library. In my opinion this shouldn't have to block us from releasing incompatible versions of the main libary, otherwise the point of having this separated repo in the first place is kind of lost.
I am anyway not too sure if the XAML-stuff is actually used by a lot of people...

Of course if you are quite motivated to work on this feel free and I'll be happy to review stuff, but I just don't think it should block the main library.

**Comment by VisualMelon** [comment]
@Jonarw yeah, I'm not worried about making it beautiful here, just providing compatibility for previous users. E.g. if there are things missing that have always been missing, that's fine. I don't really know how much use it gets, but I see questions about it semi-regularly.

If it's not an API you've used previously, it would make more sense to try to find another person for reviews, but obviously I won't object to any feedback (but wait for the moment, because I'm still fiddling, though I don't think there is much more to do).

**Comment by VisualMelon** [comment]
Well, many things are truly horrendous, but _most_ of the examples work and _most_ of the tests pass, and I don't understand why the build doesn't work, but it's getting there.

The biggest problems are all in `Plot`, where changes to the core WPF library have rendered the old implementation ineffective, and I've had to fudge things.

**Comment by VisualMelon** [comment]
I'm still not sure why I need to override `IPlotView.InvalidatePlot` for e.g. the ecclipse annotations to work properly, but the fact that Width and Height were not invoking `AppearanceChanged` suggests there could be type-by-type problems.

**Comment by VisualMelon** [comment]
Finally worked out what is going on. Added `IPlot` so that elements can report whether it was data or visuals that changed directly, and save directing everything through `IPlotView.InvalidatePlot`. Marking this as ready to review should anyone feel like looking at it. I'll probably merge it in quite soon so that I can test 'updating' an application to depend on it, whereafter I'll update the getting-started docs to reflect the (hopefully just one) change in needing to reference the contrib packages.

**Comment by VisualMelon** [comment]
- I'm not sure what LGTM is or what it's unhappy about, but I'll look into that as well (looks like it's the examples not building, which aren't in the registered CI)
 - Someone other than me should probably check the csprojs to make sure I'm not referencing anything dodgy (per snyk)

**Comment by objorke** [comment]
I removed the snyk and LGTM integrations...

**Comment by VisualMelon** [comment]
Added a wrapper and example for `HistogramSeries` to make sure everything behaves as expected.

Any objections to merging all this? If not, I'll to it tomorrow, and then get on with testing before updating the getting-started docs.

**Comment by matthew-a-thomas** [comment]
> I am anyway not too sure if the XAML-stuff is actually used by a lot of people

@Jonarw @VisualMelon It's used by my employer. I had to go digging through Git history to figure out where the `Plot.IsLegendVisible` property went when I performed the so-called "_minor_" version bump from 2.0 to 2.1. That led me here.

What's the recommended alternative to `IsLegendVisible`?

**Comment by VisualMelon** [comment]
@matthew-a-thomas yes, 2.1 should not be considered a minor release: it was very much a release for the purpose of making new functionality available that we'd other be waiting forever to release. (there is an issue somewhere where we discussed options back and forth, and basically we settled on 'people want Skia to be release, so let's release that rather than not releasing anything for years and years because no-one has enough time)

`IsLegendVisible` is still there, but it's part of `LegendBase`: 2.1 supports having multiple legends, and you need to add create and add them to the `PlotModel` yourself (there is no default legend)

See https://github.com/oxyplot/oxyplot/releases/tag/v2.1.0 for an outline of changes in 2.1

**Comment by matthew-a-thomas** [comment]
> @matthew-a-thomas yes, 2.1 should not be considered a minor release: it was very much a release for the purpose of making new functionality available that we'd other be waiting forever to release. (there is an issue somewhere where we discussed options back and forth, and basically we settled on 'people want Skia to be release, so let's release that rather than not releasing anything for years and years because no-one has enough time)
> 
> `IsLegendVisible` is still there, but it's part of `LegendBase`: 2.1 supports having multiple legends, and you need to add create and add them to the `PlotModel` yourself (there is no default legend)
> 
> See https://github.com/oxyplot/oxyplot/releases/tag/v2.1.0 for an outline of changes in 2.1

Thanks for the quick reply, @VisualMelon.

(Edit: sorry I misread your reply. Took this part out)

Thanks for the pointer to the model. I'm not very familiar with OxyPlot. These things didn't work:

* Setting `Plot.ActualModel.IsLegendVisible` to `true`
* Adding an instance of `OxyPlot.Legends.Legend` to `Plot.ActualModel.Legends`

What ended up working for me was this:

* Add an instance of `OxyPlot.Wpf.Legend` to `Plot.Legends`

I encapsulated this into an attached property for posterity:

```xml
<!-- .csproj -->
<ItemGroup>
  <PackageReference Include="OxyPlot.Contrib.Wpf">
    <Version>2.1.0</Version>
  </PackageReference>
  <PackageReference Include="OxyPlot.Wpf">
    <Version>2.1.0</Version>
  </PackageReference>
</ItemGroup>
```

```csharp
// OxyPlotHacks.cs
using System.Windows;
using OxyPlot.Wpf;

public sealed class OxyPlotHacks : DependencyObject
{
    public static readonly DependencyProperty IsLegendVisibleProperty = DependencyProperty.RegisterAttached(
        "IsLegendVisible",
        typeof(bool),
        typeof(OxyPlotHacks),
        new PropertyMetadata(default(bool), HandleIsLegendVisibleChanged));

    static void HandleIsLegendVisibleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var plot = (Plot)d;
        var legends = plot.Legends;
        legends.Clear();
        if (e.NewValue is true)
        {
            legends.Add(new Legend());
        }
    }

    [AttachedPropertyBrowsableForType(typeof(Plot))]
    public static bool GetIsLegendVisible(Plot plot) => (bool)plot.GetValue(IsLegendVisibleProperty);

    public static void SetIsLegendVisible(Plot plot, bool value) => plot.SetValue(IsLegendVisibleProperty, value);
}
```

Usage:

```xaml
<UserControl
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:oxy="http://oxyplot.org/wpf/contrib"
  xmlns:local="clr-namespace:YourNamespaceHere">
  <oxy:Plot local:OxyPlotHacks.IsLegendVisible="True"/>
</UserControl>
```

**Comment by VisualMelon** [comment]
@matthew-a-thomas you can see an example of the intended means of adding a legend XAML here, should it not be clear (though I appreciate you may need the hack for other reasons): https://github.com/oxyplot/oxyplot-contrib/blob/develop/Source/Examples/WPF/WpfExamples/Examples/BindingObservableCollectionDemo/MainWindow.xaml#L30

You can put a binding to the `Legend.IsLegendVisible` property on the `Legend` itself if useful.

**Comment by matthew-a-thomas** [comment]
@VisualMelon Oh yeah, that's much simpler to just instantiate it in the XAML. Yeah I'll throw away my hack class. Thank you thank you!!

**Comment by VisualMelon** [comment]
For reference, `ActualModel` is the `PlotModel` generated from the WPF/XAML 'native' Plot: ideally you shouldn't have to interact with this; if you are creating the whole `PlotModel` yourself, then it's better to use the OxyPlot.WPF.PlotView rather than the contrib Plot.

If you have short-form questions about how anything works, feel free to ask in the oxyplot gitter https://gitter.im/oxyplot/oxyplot and I'll try to get back to you

**Pull request merged**
